name = "ContinuousTimeEconTools"
uuid = "cebab7d8-d453-44c6-968c-78466cef4c7c"
authors = ["Ruairidh South <rsouth@princeton.edu> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
